backend:
  name: github
  repo: picohook/libedge-website
  branch: main
  base_url: https://api.github.com
  auth_endpoint: https://github.com/login/oauth/authorize
  app_id: # GitHub OAuth App ID'nizi buraya ekleyin
  # Aşağıdaki ayarlar Cloudflare Pages için gereklidir
  api_root: https://api.github.com
  site_domain: libedge-website.pages.dev

# Media library ayarları
media_folder: "assets/images/uploads"
public_folder: "/assets/images/uploads"

# İstemci tarafı kimlik doğrulama için özel ayarlar
local_backend: false

# Collections
collections:
  - name: "announcements"
    label: "Duyurular"
    label_singular: "Duyuru"
    description: "Web sitesindeki duyuruları buradan ekleyebilir veya düzenleyebilirsiniz."
    files:
      - file: "duyurular.json"
        label: "Tüm Duyurular"
        name: "all_announcements"
        fields:
          - {label: "Duyuru Listesi", name: "items", widget: "list", fields: [
              {label: "Başlık", name: "title", widget: "string"},
              {label: "Tarih", name: "date", widget: "datetime", format: "YYYY-MM-DD"},
              {label: "Kategori", name: "category", widget: "select", options: ["urgent", "new-product", "event", "maintenance", "general"]},
              {label: "Özet (Kısa Açıklama)", name: "summary", widget: "text"},
              {label: "Tam İçerik (Detaylı Açıklama)", name: "full_content", widget: "markdown"}
            ]}