name = "form-handler"
main = "backend/src/index.js"
compatibility_date = "2024-09-01"

name = "view-counter"
main = "backend/src/index.js"
compatibility_date = "2025-10-12"

[[kv_namespaces]]
binding = "VIEW_COUNTS" # Worker kodunda kullanılacak isim (env.KV)
id = "13f653d049d248cba1bdba46345302b4" # Kopyaladığınız Namespace ID'sini buraya yapıştırın