-- =====================================================================
-- 0002_runtime_indexes.sql
-- Compatibility placeholder.
--
-- Runtime indexes are useful, but older local databases may not yet have
-- every column referenced by the original index set. Failing here blocks
-- later functional migrations such as newsletter support.
--
-- If needed, indexes can be added later in targeted compatibility
-- migrations after the schema is guaranteed to match production.
-- =====================================================================
