INSERT INTO products (
  slug, name, category, region,
  default_access_type, default_access_url,
  access_tags_json,
  card_visible,
  ra_enabled, ra_delivery_mode, ra_origin_host, ra_origin_landing_path,
  ra_requires_tunnel, ra_host_allowlist_json
) VALUES
('annual-reviews', 'Annual Reviews', 'Fen & Matematik', 'Türkiye', 'ip', 'https://www.annualreviews.org', '["EKUAL"]', 1, 1, 'path_proxy', 'www.annualreviews.org', NULL, 1, '["www.annualreviews.org","annualreviews.org"]'),
('cab-abstracts', 'CAB Abstracts', 'Fen & Matematik', 'Türkiye', 'ip', 'https://www.cabdirect.org', '["EKUAL"]', 1, 1, 'path_proxy', 'www.cabdirect.org', NULL, 1, '["www.cabdirect.org","cabdirect.org"]'),
('cambridge-university-press', 'Cambridge University Press (CUP)', 'Genel', 'Türkiye', 'ip', 'https://www.cambridge.org/core', '["EKUAL"]', 1, 1, 'path_proxy', 'www.cambridge.org', '/core', 1, '["www.cambridge.org","cambridge.org"]'),
('dynamed', 'DynaMed', 'Sağlık', 'Türkiye', 'ip', 'https://www.dynamed.com', '["EKUAL"]', 1, 1, 'path_proxy', 'www.dynamed.com', NULL, 1, '["www.dynamed.com","dynamed.com"]'),
('emerald-premier', 'Emerald Premier eJournal', 'İşletme, Ekonomi, Finans', 'Türkiye', 'ip', 'https://www.emerald.com/insight', '["EKUAL"]', 1, 1, 'path_proxy', 'www.emerald.com', '/insight', 1, '["www.emerald.com","emerald.com"]'),
('ieee', 'IEEE', 'Fen & Matematik', 'Türkiye', 'ip', 'https://ieeexplore.ieee.org', '["EKUAL"]', 1, 1, 'path_proxy', 'ieeexplore.ieee.org', NULL, 1, '["ieeexplore.ieee.org","ieee.org"]'),
('intihal-net', 'İntihal.net (Akademik İntihal)', 'Genel', 'Türkiye', 'email_password_external', 'https://www.intihal.net', '["EKUAL"]', 1, 0, 'path_proxy', NULL, NULL, 1, NULL),
('ithenticate', 'iThenticate', 'Genel', 'Türkiye', 'email_password_external', 'https://www.ithenticate.com', '["EKUAL"]', 1, 0, 'path_proxy', NULL, NULL, 1, NULL),
('jstor', 'JSTOR Archive Journal Content', 'Genel', 'Türkiye', 'ip', 'https://www.jstor.org', '["EKUAL"]', 1, 1, 'path_proxy', 'www.jstor.org', NULL, 1, '["www.jstor.org","jstor.org"]'),
('lexiqamus', 'Lexiqamus', 'Genel', 'Türkiye', 'ip', 'https://www.lexiqamus.com', '["EKUAL"]', 1, 1, 'path_proxy', 'www.lexiqamus.com', NULL, 1, '["www.lexiqamus.com","lexiqamus.com"]'),
('military-big-data', 'Military Big Data', 'Fen & Matematik', 'Türkiye', 'ip', 'https://mildata.net/Panel/Home', '["EKUAL"]', 1, 1, 'path_proxy', 'mildata.net', '/Panel/Home', 1, '["mildata.net"]'),
('muteferriqa', 'Muteferriqa', 'Genel', 'Türkiye', 'ip', 'https://portal.muteferriqa.com/', '["EKUAL"]', 1, 1, 'path_proxy', 'portal.muteferriqa.com', NULL, 1, '["portal.muteferriqa.com","muteferriqa.com"]'),
('nejm', 'New England Journal of Medicine', 'Sağlık', 'Türkiye', 'ip', 'https://www.nejm.org', '["EKUAL"]', 1, 1, 'path_proxy', 'www.nejm.org', NULL, 1, '["www.nejm.org","nejm.org"]'),
('nejm-evidence', 'NEJM Evidence Bundle', 'Sağlık', 'Türkiye', 'ip', 'https://evidence.nejm.org', '["EKUAL"]', 1, 1, 'path_proxy', 'evidence.nejm.org', NULL, 1, '["evidence.nejm.org","nejm.org"]'),
('oxford-university-press', 'Oxford University Press (OUP)', 'Genel', 'Türkiye', 'ip', 'https://academic.oup.com', '["EKUAL"]', 1, 1, 'path_proxy', 'academic.oup.com', NULL, 1, '["academic.oup.com","oup.com"]'),
('proquest-dissertations', 'ProQuest Dissertations & Theses', 'Genel', 'Türkiye', 'ip', 'https://www.proquest.com', '["EKUAL"]', 1, 1, 'path_proxy', 'www.proquest.com', NULL, 1, '["www.proquest.com","proquest.com"]'),
('rsc', 'The Royal Society of Chemistry (RSC)', 'Fen & Matematik', 'Türkiye', 'ip', 'https://pubs.rsc.org', '["EKUAL"]', 1, 1, 'path_proxy', 'pubs.rsc.org', NULL, 1, '["pubs.rsc.org","rsc.org"]'),
('sciencedirect', 'ScienceDirect Freedom Collection', 'Fen & Matematik', 'Türkiye', 'ip', 'https://www.sciencedirect.com', '["EKUAL"]', 1, 1, 'path_proxy', 'www.sciencedirect.com', NULL, 1, '["www.sciencedirect.com","sciencedirect.com"]'),
('scopus', 'Scopus', 'Fen & Matematik', 'Türkiye', 'ip', 'https://www.scopus.com', '["EKUAL"]', 1, 1, 'path_proxy', 'www.scopus.com', NULL, 1, '["www.scopus.com","scopus.com"]'),
('springerlink', 'SpringerLink | Palgrave | Adis Dergileri', 'Genel', 'Türkiye', 'ip', 'https://link.springer.com', '["EKUAL"]', 1, 1, 'path_proxy', 'link.springer.com', NULL, 1, '["link.springer.com","springer.com"]'),
('nature', 'Nature | Academic Dergileri', 'Fen & Matematik', 'Türkiye', 'ip', 'https://www.nature.com', '["EKUAL"]', 1, 1, 'path_proxy', 'www.nature.com', NULL, 1, '["www.nature.com","nature.com"]'),
('taylor-francis', 'Taylor & Francis', 'Genel', 'Türkiye', 'ip', 'https://www.taylorfrancis.com', '["EKUAL"]', 1, 1, 'path_proxy', 'www.taylorfrancis.com', NULL, 1, '["www.taylorfrancis.com","taylorfrancis.com"]'),
('turcademy', 'Turcademy', 'Genel', 'Türkiye', 'ip', 'https://www.turcademy.com', '["EKUAL"]', 1, 1, 'path_proxy', 'www.turcademy.com', NULL, 1, '["www.turcademy.com","turcademy.com"]'),
('turnitin', 'Turnitin', 'Genel', 'Türkiye', 'email_password_external', 'https://www.turnitin.com', '["EKUAL"]', 1, 0, 'path_proxy', NULL, NULL, 1, NULL),
('web-of-science', 'Web of Science', 'Fen & Matematik', 'Türkiye', 'ip', 'https://www.webofscience.com', '["EKUAL"]', 1, 1, 'path_proxy', 'www.webofscience.com', NULL, 1, '["www.webofscience.com","webofscience.com"]'),
('wiley', 'Wiley Online Library', 'Genel', 'Türkiye', 'ip', 'https://onlinelibrary.wiley.com', '["EKUAL"]', 1, 1, 'path_proxy', 'onlinelibrary.wiley.com', NULL, 1, '["onlinelibrary.wiley.com","wiley.com"]')
ON CONFLICT(slug) DO UPDATE SET
  name = excluded.name,
  category = excluded.category,
  region = COALESCE(NULLIF(products.region, ''), excluded.region),
  default_access_type = excluded.default_access_type,
  default_access_url = excluded.default_access_url,
  access_tags_json = excluded.access_tags_json,
  card_visible = COALESCE(products.card_visible, excluded.card_visible),
  ra_enabled = excluded.ra_enabled,
  ra_delivery_mode = excluded.ra_delivery_mode,
  ra_origin_host = excluded.ra_origin_host,
  ra_origin_landing_path = excluded.ra_origin_landing_path,
  ra_requires_tunnel = excluded.ra_requires_tunnel,
  ra_host_allowlist_json = excluded.ra_host_allowlist_json;
