INSERT INTO products (
  slug, name, category, region,
  default_access_type, default_access_url,
  access_tags_json,
  card_visible,
  ra_enabled, ra_delivery_mode, ra_origin_host, ra_origin_landing_path,
  ra_requires_tunnel, ra_host_allowlist_json
) VALUES
('annual-reviews', 'Annual Reviews', 'Fen & Matematik', 'Türkiye', 'ip', 'https://www.annualreviews.org', '["EKUAL"]', 1, 1, 'session_host_proxy', 'www.annualreviews.org', NULL, 1, '["www.annualreviews.org","annualreviews.org"]'),
('cab-abstracts', 'CAB Abstracts', 'Fen & Matematik', 'Türkiye', 'ip', 'https://www.cabidigitallibrary.org/product/ca', '["EKUAL"]', 1, 1, 'stable_host_proxy', 'www.cabidigitallibrary.org', '/product/ca', 1, '["www.cabidigitallibrary.org","cabidigitallibrary.org","www.cabi.org","cabi.org","www.cabdirect.org","cabdirect.org"]'),
('cambridge-university-press', 'Cambridge University Press (CUP)', 'Genel', 'Türkiye', 'ip', 'https://www.cambridge.org/core', '["EKUAL"]', 1, 1, 'session_host_proxy', 'www.cambridge.org', '/core', 1, '["www.cambridge.org","cambridge.org"]'),
('dynamed', 'DynaMed', 'Sağlık', 'Türkiye', 'ip', 'https://www.dynamed.com', '["EKUAL"]', 1, 1, 'session_host_proxy', 'www.dynamed.com', NULL, 1, '["www.dynamed.com","dynamed.com"]'),
('emerald-premier', 'Emerald Premier eJournal', 'İşletme, Ekonomi, Finans', 'Türkiye', 'ip', 'https://www.emerald.com/insight/', '["EKUAL"]', 1, 1, 'stable_host_proxy', 'www.emerald.com', '/insight/', 1, '["www.emerald.com","emerald.com"]'),
('ieee', 'IEEE', 'Fen & Matematik', 'Türkiye', 'ip', 'https://ieeexplore.ieee.org', '["EKUAL"]', 1, 1, 'session_host_proxy', 'ieeexplore.ieee.org', NULL, 1, '["ieeexplore.ieee.org","ieee.org"]'),
('intihal-net', 'İntihal.net (Akademik İntihal)', 'Genel', 'Türkiye', 'email_password_external', 'https://www.intihal.net', '["EKUAL"]', 1, 0, 'path_proxy', NULL, NULL, 1, NULL),
('ithenticate', 'iThenticate', 'Genel', 'Türkiye', 'email_password_external', 'https://www.ithenticate.com', '["EKUAL"]', 1, 0, 'path_proxy', NULL, NULL, 1, NULL),
('jstor', 'JSTOR Archive Journal Content', 'Genel', 'Türkiye', 'ip', 'https://www.jstor.org', '["EKUAL"]', 1, 1, 'session_host_proxy', 'www.jstor.org', NULL, 1, '["www.jstor.org","jstor.org"]'),
('lexiqamus', 'Lexiqamus', 'Genel', 'Türkiye', 'ip', 'https://www.lexiqamus.com', '["EKUAL"]', 1, 1, 'session_host_proxy', 'www.lexiqamus.com', NULL, 1, '["www.lexiqamus.com","lexiqamus.com"]'),
('military-big-data', 'Military Big Data', 'Fen & Matematik', 'Türkiye', 'ip', 'https://mildata.net/Panel/Home', '["EKUAL"]', 1, 1, 'session_host_proxy', 'mildata.net', '/Panel/Home', 1, '["mildata.net"]'),
('muteferriqa', 'Muteferriqa', 'Genel', 'Türkiye', 'ip', 'https://portal.muteferriqa.com/', '["EKUAL"]', 1, 1, 'session_host_proxy', 'portal.muteferriqa.com', NULL, 1, '["portal.muteferriqa.com","muteferriqa.com"]'),
('nejm', 'New England Journal of Medicine', 'Sağlık', 'Türkiye', 'ip', 'https://www.nejm.org', '["EKUAL"]', 1, 1, 'session_host_proxy', 'www.nejm.org', NULL, 1, '["www.nejm.org","nejm.org"]'),
('nejm-evidence', 'NEJM Evidence Bundle', 'Sağlık', 'Türkiye', 'ip', 'https://evidence.nejm.org', '["EKUAL"]', 1, 1, 'session_host_proxy', 'evidence.nejm.org', NULL, 1, '["evidence.nejm.org","nejm.org"]'),
('oxford-university-press', 'Oxford University Press (OUP)', 'Genel', 'Türkiye', 'ip', 'https://academic.oup.com', '["EKUAL"]', 1, 1, 'session_host_proxy', 'academic.oup.com', NULL, 1, '["academic.oup.com","oup.com"]'),
('proquest-dissertations', 'ProQuest Dissertations & Theses', 'Genel', 'Türkiye', 'ip', 'https://www.proquest.com', '["EKUAL"]', 1, 1, 'session_host_proxy', 'www.proquest.com', '/ip', 1, '["www.proquest.com","proquest.com","search.proquest.com","gateway.proquest.com","openurl.proquest.com","media2.proquest.com","ebookcentral.proquest.com","explore.proquest.com","fedsearch.proquest.com","pqrc.proquest.com","prq.st","proquest.umi.com","sanborn.umi.com","li.proquest.com","literature.proquest.com","congressional.proquest.com","datasets.proquest.com","dialog.proquest.com","digitalmicrofilm.proquest.com","digitalmicrofilm1.proquest.com","newspaperslibrary.proquest.com","regulatoryinsight.proquest.com","statistical.proquest.com","statabs.proquest.com","wt3.proquest.com","hv.proquest.com","hv.conquestsystems.com","statab.conquestsystems.com","online.culturegrams.com","www.proquestk12.com"]'),
('rsc', 'The Royal Society of Chemistry (RSC)', 'Fen & Matematik', 'Türkiye', 'ip', 'https://pubs.rsc.org', '["EKUAL"]', 1, 1, 'session_host_proxy', 'pubs.rsc.org', NULL, 1, '["pubs.rsc.org","rsc.org"]'),
('sciencedirect', 'ScienceDirect Freedom Collection', 'Fen & Matematik', 'Türkiye', 'ip', 'https://www.sciencedirect.com', '["EKUAL"]', 1, 1, 'session_host_proxy', 'www.sciencedirect.com', NULL, 1, '["www.sciencedirect.com","sciencedirect.com","doi.org","dx.doi.org","linkinghub.elsevier.com","id.elsevier.com","www.elsevier.com","admintool.elsevier.com","help-admintool.elsevier.com","tableau-admintool.elsevier.com","online.tableau.com","*.els-cdn.com","sciverse-shindig.elsevier.com"]'),
('scopus', 'Scopus', 'Fen & Matematik', 'Türkiye', 'ip', 'https://www.scopus.com', '["EKUAL"]', 1, 1, 'session_host_proxy', 'www.scopus.com', '/home.url', 1, '["www.scopus.com","scopus.com","www2.scopus.com","components.scopus.com","id.elsevier.com","www.elsevier.com"]'),
('springerlink', 'SpringerLink | Palgrave | Adis Dergileri', 'Genel', 'Türkiye', 'ip', 'https://link.springer.com', '["EKUAL"]', 1, 1, 'session_host_proxy', 'link.springer.com', '/search', 1, '["link.springer.com","idp.springer.com","rd.springer.com","springer.com","www.springer.com","www.link.springer.com","www.springerlink.com","springerlink.com","download.springer.com","ebooks.springerlink.com","adisonline.com","www.adisonline.com","link.springer.de","springer.de","aa.springer.de","link.springer-ny.com","springer-ny.com","sprn.gr"]'),
('nature', 'Nature | Academic Dergileri', 'Fen & Matematik', 'Türkiye', 'ip', 'https://www.nature.com', '["EKUAL"]', 1, 1, 'session_host_proxy', 'www.nature.com', '/', 1, '["www.nature.com","nature.com","idp.nature.com","doi.org","dx.doi.org","scholar.google.com","search.nature.com","nano.nature.com","links.ealert.nature.com","arabicedition.nature.com","ajandrology.com","www.ajandrology.com","labanimal.com","www.labanimal.com","naturesj.com","www.naturesj.com","npgjournals.com","www.npgjournals.com","natureasia.com","ensighten.com","nexus.ensighten.com"]'),
('taylor-francis', 'Taylor & Francis', 'Genel', 'Türkiye', 'ip', 'https://www.taylorfrancis.com', '["EKUAL"]', 1, 1, 'session_host_proxy', 'www.taylorfrancis.com', NULL, 1, '["www.taylorfrancis.com","taylorfrancis.com"]'),
('turcademy', 'Turcademy', 'Genel', 'Türkiye', 'ip', 'https://www.turcademy.com', '["EKUAL"]', 1, 1, 'session_host_proxy', 'www.turcademy.com', NULL, 1, '["www.turcademy.com","turcademy.com"]'),
('turnitin', 'Turnitin', 'Genel', 'Türkiye', 'email_password_external', 'https://www.turnitin.com', '["EKUAL"]', 1, 0, 'path_proxy', NULL, NULL, 1, NULL),
('web-of-science', 'Web of Science', 'Fen & Matematik', 'Türkiye', 'ip', 'https://www.webofscience.com', '["EKUAL"]', 1, 1, 'session_host_proxy', 'www.webofscience.com', NULL, 1, '["www.webofscience.com","webofscience.com"]'),
('wiley', 'Wiley Online Library', 'Genel', 'Türkiye', 'ip', 'https://onlinelibrary.wiley.com', '["EKUAL"]', 1, 1, 'session_host_proxy', 'onlinelibrary.wiley.com', NULL, 1, '["onlinelibrary.wiley.com","*.onlinelibrary.wiley.com","www.onlinelibrary.wiley.com","api.wiley.com","doi.wiley.com","el.wiley.com","wiley.com","www.wiley.com","wileyonlinelibrary.com","www.wileyonlinelibrary.com","wileyopenaccess.com","www.wileyopenaccess.com","interscience.wiley.com","www.interscience.wiley.com","www3.interscience.wiley.com","mrw.interscience.wiley.com","www.mrw.interscience.wiley.com","pericles.one-lts.literatumonline.com","wires.wiley.com","www.wires.wiley.com"]')
ON CONFLICT(slug) DO UPDATE SET
  name = excluded.name,
  category = excluded.category,
  region = COALESCE(NULLIF(products.region, ''), excluded.region),
  default_access_type = excluded.default_access_type,
  default_access_url = excluded.default_access_url,
  access_tags_json = excluded.access_tags_json,
  card_visible = COALESCE(products.card_visible, excluded.card_visible),
  ra_enabled = excluded.ra_enabled,
  ra_delivery_mode = excluded.ra_delivery_mode,
  ra_origin_host = excluded.ra_origin_host,
  ra_origin_landing_path = excluded.ra_origin_landing_path,
  ra_requires_tunnel = excluded.ra_requires_tunnel,
  ra_host_allowlist_json = excluded.ra_host_allowlist_json;
