name = "view-counter"
main = "index.js"
compatibility_date = "2025-10-12"

[[durable_objects.bindings]]
name = "COUNTER"
class_name = "MyDurableObject"

[[migrations]]
tag = "v1"
new_classes = ["MyDurableObject"]