# Sitenizin GitHub deposu için backend ayarları
backend:
  name: github
  repo: picohook/libedge-website # ÖNEMLİ: Kendi GitHub kullanıcı adınızı ve repo adınızı yazın
  branch: main # veya master (varsayılan branch'iniz hangisiyse)
  base_url: https://sveltia-cms-auth.agursel.workers.dev/

# Panelde yüklenecek resim gibi dosyaların nereye kaydedileceği
media_folder: "assets/images/uploads"
public_folder: "/assets/images/uploads"

# Yönetilecek içerik koleksiyonları
collections:
  - name: "announcements" # Koleksiyonun kimliği (değiştirmeyin)
    label: "Duyurular" # Panelde görünecek isim
    label_singular: "Duyuru"
    description: "Web sitesindeki duyuruları buradan ekleyebilir veya düzenleyebilirsiniz."
    # Bu koleksiyonun birden çok dosya yerine tek bir dosyayı yöneteceğini belirtir
    files:
      - file: "duyurular.json" # Düzenlenecek dosyanın yolu
        label: "Tüm Duyurular"
        name: "all_announcements"
        # Dosyanın içindeki liste yapısını ve form alanlarını tanımlar
        fields:
          - {label: "Duyuru Listesi", name: "items", widget: "list", fields: [
              {label: "Başlık", name: "title", widget: "string"},
              {label: "Tarih", name: "date", widget: "datetime", format: "YYYY-MM-DD"},
              {label: "Kategori", name: "category", widget: "select", options: ["urgent", "new-product", "event", "maintenance", "general"]},
              {label: "Özet (Kısa Açıklama)", name: "summary", widget: "text"},
              {label: "Tam İçerik (Detaylı Açıklama)", name: "full_content", widget: "markdown"}
            ]}